preset: angular
branches:
  - main
tagFormat: 'v${version}'
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - successComment: false
      failComment: false
      releasedLabels: false
  - - '@semantic-release/exec'
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
        goreleaser release --release-notes /tmp/release-notes.md --clean
