name: 'setup tfenv'
description: 'Setup and configure tfenv.'
runs:
  using: "composite"
  steps:
    - name: Checkout tfenv
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
          repository: tfutils/tfenv
          ref: v3.0.0
          path: .tfenv
          persist-credentials: false

    - name: Extend Path
      shell: bash
      run: |
        mv "${GITHUB_WORKSPACE}/.tfenv" "/opt/.tfenv"
        echo "/opt/.tfenv/bin" >> "${GITHUB_PATH}"

    - name: Install terraform
      shell: bash
      run: tfenv install

    - name: Use terraform
      shell: bash
      run: tfenv use
